package danmaku

import "arcana-world/internal/i18n"

// 协议事实独立摘录自已归档的 bilive_client 模式定义：
// https://github.com/ShmilyChen/bilive_client/blob/master/bilive/@types/danmaku.d.ts
// 命令名已与 https://github.com/xuan25/BiliLiveCmds/blob/master/sum_cmd_list.js 交叉核对。
// 模式定义中的 PK_BATTLE_PREP 接口对应线格式命令 PK_BATTLE_PRE；
// Room_Admin_Entrance 对应现代命令 room_admin_entrance，并非另一种拼写。
// 基础接口不是命令。数组保留解码后的内容；枚举
// 数字和字符串保持原样，不作解释。连击汇总和欢迎通知
// 仅作为详情，绝不计作额外的付费礼物或上舰购买。
var legacyCommandSpecs = map[string]commandSpec{
	"ACTIVITY_BANNER_CLOSE": {
		title: i18n.DanmakuLegacyActivityBannerClose,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.banner_type", 'n'},
		},
	},
	"ACTIVITY_BANNER_RED_NOTICE": {
		title: i18n.DanmakuLegacyActivityBannerRedNotice,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.type", 's'},
			{"data.icon", 's'},
		},
	},
	"ACTIVITY_BANNER_RED_NOTICE_CLOSE": {
		title: i18n.DanmakuLegacyActivityBannerRedNoticeClose,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.type", 's'},
		},
	},
	"ACTIVITY_BANNER_UPDATE": {
		title: i18n.DanmakuLegacyActivityBannerUpdate,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.title", 's'},
			{"data.cover", 's'},
			{"data.background", 's'},
			{"data.jump_url", 's'},
			{"data.title_color", 's'},
			{"data.closeable", 'n'},
			{"data.banner_type", 'n'},
			{"data.weight", 'n'},
			{"data.web_text", 's'},
			{"data.web_cover", 's'},
		},
	},
	"ACTIVITY_MATCH_GIFT": {
		title: i18n.DanmakuLegacyActivityMatchGift,
		fields: []commandField{
			{"data.action", 's'},
			{"data.status", 'n'},
			{"data.detail.match_id", 'i'},
			{"data.detail.home.team_name", 's'},
			{"data.detail.home.url", 's'},
			{"data.detail.home.ratio", 's'},
			{"data.detail.home.score", 'n'},
			{"data.detail.home.gift_info", 'a'},
			{"data.detail.visit.team_name", 's'},
			{"data.detail.visit.url", 's'},
			{"data.detail.visit.ratio", 's'},
			{"data.detail.visit.score", 'n'},
			{"data.detail.visit.gift_info", 'a'},
		},
	},
	"ANIMATION": {
		title: i18n.DanmakuLegacyAnimation,
		fields: []commandField{
			{"data.animation", 's'},
			{"data.type", 's'},
			{"data.weights", 'n'},
			{"data.uid", 'i'},
		},
	},
	"BOSS_BATTLE": {
		title: i18n.DanmakuLegacyBossBattle,
		fields: []commandField{
			{"data.uname", 's'},
			{"data.gift_id", 'i'},
			{"data.number", 'n'},
			{"data.injury", 'n'},
			{"data.uid", 'i'},
			{"data.room_id", 'i'},
			{"data.integral", 'n'},
		},
	},
	"BOSS_ENERGY": {
		title: i18n.DanmakuLegacyBossEnergy,
		fields: []commandField{
			{"data.level", 'n'},
			{"data.valve", 'n'},
			{"data.current", 'n'},
		},
	},
	"BOSS_INFO": {
		title: i18n.DanmakuLegacyBossInfo,
		fields: []commandField{
			{"data.boss_status", 'n'},
			{"data.time", 'n'},
			{"data.energy_level", 'n'},
			{"data.base_level", 'n'},
			{"data.boss_id", 'i'},
			{"data.boss_type", 's'},
			{"data.uid", 'i'},
			{"data.play_status", 'n'},
			{"data.energy_charging.level", 'n'},
			{"data.energy_charging.valve", 'n'},
			{"data.energy_charging.current", 'n'},
			{"data.energy_charging.energy_level", 'n'},
			{"data.battle.total_blood_volume", 'n'},
			{"data.battle.residual_blood_volume", 'n'},
			{"data.battle.energy_value", 'n'},
			{"data.battle.boss_id", 'i'},
			{"data.battle.boss_status", 'n'},
			{"data.battle.ts", 'n'},
			{"data.battle.boss_name", 's'},
		},
	},
	"BOSS_INJURY": {
		title: i18n.DanmakuLegacyBossInjury,
		fields: []commandField{
			{"data.total_blood_volume", 'n'},
			{"data.residual_blood_volume", 'n'},
			{"data.energy_value", 'n'},
			{"data.boss_id", 'i'},
			{"data.is_query", 'n'},
		},
	},
	"BOX_ACTIVITY_START": {
		title: i18n.DanmakuLegacyBoxActivityStart,
		fields: []commandField{
			{"aid", 'n'},
			{"data.activity_id", 'i'},
			{"data.jump_url", 's'},
			{"data.weight", 'n'},
			{"data.closeable", 'n'},
			{"data.title", 's'},
			{"data.title_color", 's'},
			{"data.activity_pic", 's'},
			{"data.background", 's'},
			{"data.current_round", 'n'},
			{"data.typeB", 'a'},
		},
	},
	"CHANGE_ROOM_INFO": {
		title: i18n.DanmakuLegacyChangeRoomInfo,
		fields: []commandField{
			{"background", 's'},
		},
	},
	"COMBO_END": {
		title: i18n.DanmakuLegacyComboEnd,
		fields: []commandField{
			{"data.uname", 's'},
			{"data.r_uname", 's'},
			{"data.combo_num", 'n'},
			{"data.price", 'n'},
			{"data.gift_name", 's'},
			{"data.gift_id", 'i'},
			{"data.start_time", 'n'},
			{"data.end_time", 'n'},
			{"data.guard_level", 'n'},
		},
	},
	"COMBO_SEND": {
		title: i18n.DanmakuLegacyComboSend,
		fields: []commandField{
			{"data.uid", 'i'},
			{"data.uname", 's'},
			{"data.combo_num", 'n'},
			{"data.gift_name", 's'},
			{"data.gift_id", 'i'},
			{"data.action", 's'},
			{"data.combo_id", 's'},
		},
	},
	"DAILY_QUEST_NEWDAY": {
		title: i18n.DanmakuLegacyDailyQuestNewday,
	},
	"DAILY_QUEST_REWARD": {
		title: i18n.DanmakuLegacyDailyQuestReward,
		fields: []commandField{
			{"data.aid", 'n'},
			{"data.room_id", 'i'},
		},
	},
	"FREE_GIFT_BUBBLE": {
		title: i18n.DanmakuLegacyFreeGiftBubble,
		fields: []commandField{
			{"data.text", 's'},
			{"data.color", 's'},
			{"data.highlight", 's'},
			{"data.url", 's'},
			{"data.is_detail", 'n'},
		},
	},
	"GUARD_LOTTERY_START": {
		title: i18n.DanmakuLegacyGuardLotteryStart,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.roomid", 'i'},
			{"data.message", 's'},
			{"data.type", 's'},
			{"data.privilege_type", 'n'},
			{"data.link", 's'},
			{"data.payflow_id", 's'},
			{"data.lottery.id", 'i'},
			{"data.lottery.sender.uid", 'i'},
			{"data.lottery.sender.uname", 's'},
			{"data.lottery.sender.face", 's'},
			{"data.lottery.keyword", 's'},
			{"data.lottery.privilege_type", 'n'},
			{"data.lottery.time", 'n'},
			{"data.lottery.status", 'n'},
			{"data.lottery.mobile_display_mode", 'n'},
			{"data.lottery.mobile_static_asset", 's'},
			{"data.lottery.mobile_animation_asset", 's'},
		},
	},
	"GUARD_MSG": {
		title: i18n.DanmakuLegacyGuardMsg,
		fields: []commandField{
			{"msg", 's'},
			{"buy_type", 'n'},
		},
	},
	"HOUR_RANK_AWARDS": {
		title: i18n.DanmakuLegacyHourRankAwards,
		fields: []commandField{
			{"action", 's'},
			{"data.roomid", 'i'},
			{"data.ruid", 'i'},
			{"data.uname", 's'},
			{"data.face", 's'},
			{"data.rank_desc", 's'},
			{"data.content", 's'},
			{"data.life_cycle", 'n'},
			{"data.award_desc", 's'},
			{"data.award_url", 's'},
			{"data.award_warn", 's'},
			{"data.button_content", 's'},
			{"data.jump_content", 's'},
			{"data.jump_url", 's'},
			{"data.rank_content", 's'},
			{"data.title", 's'},
			{"data.web_jump_url", 's'},
		},
	},
	"LITTLE_TIPS": {
		title: i18n.DanmakuLegacyLittleTips,
		fields: []commandField{
			{"data.msg", 's'},
		},
	},
	"LOL_ACTIVITY": {
		title: i18n.DanmakuLegacyLolActivity,
		fields: []commandField{
			{"data.action", 's'},
			{"data.match_id", 'i'},
			{"data.timestamp", 'n'},
		},
	},
	"LOTTERY_START": {
		title: i18n.DanmakuLegacyLotteryStart,
		fields: []commandField{
			{"data.id", 'i'},
			{"data.roomid", 'i'},
			{"data.message", 's'},
			{"data.type", 's'},
			{"data.privilege_type", 'n'},
			{"data.link", 's'},
			{"data.payflow_id", 's'},
			{"data.lottery.id", 'i'},
			{"data.lottery.sender.uid", 'i'},
			{"data.lottery.sender.uname", 's'},
			{"data.lottery.sender.face", 's'},
			{"data.lottery.keyword", 's'},
			{"data.lottery.privilege_type", 'n'},
			{"data.lottery.time", 'n'},
			{"data.lottery.status", 'n'},
			{"data.lottery.mobile_display_mode", 'n'},
			{"data.lottery.mobile_static_asset", 's'},
			{"data.lottery.mobile_animation_asset", 's'},
		},
	},
	"LUCK_GIFT_AWARD_MASTER": {
		title: i18n.DanmakuLegacyLuckGiftAwardMaster,
		fields: []commandField{
			{"data.uid", 'i'},
			{"data.gift_name", 's'},
			{"data.coin", 's'},
			{"data.gift_icon", 's'},
			{"data.start_time", 's'},
			{"data.end_time", 's'},
			{"data.user_uname", 's'},
		},
	},
	"LUCK_GIFT_AWARD_USER": {
		title: i18n.DanmakuLegacyLuckGiftAwardUser,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.uid", 'i'},
			{"data.gift_name", 's'},
			{"data.coin", 's'},
			{"data.gift_icon", 's'},
			{"data.rate", 'n'},
			{"data.start_time", 's'},
			{"data.end_time", 's'},
		},
	},
	"MESSAGEBOX_USER_GAIN_MEDAL": {
		title: i18n.DanmakuLegacyMessageboxUserGainMedal,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.uid", 'i'},
			{"data.up_uid", 'i'},
			{"data.medal_id", 'i'},
			{"data.medal_name", 's'},
			{"data.medal_level", 'n'},
			{"data.medal_color", 'n'},
			{"data.msg_title", 's'},
			{"data.msg_content", 's'},
			{"data.normal_color", 'n'},
			{"data.highlight_color", 'n'},
			{"data.intimacy", 'n'},
			{"data.next_intimacy", 'n'},
			{"data.today_feed", 'n'},
			{"data.day_limit", 'n'},
		},
	},
	"new_anchor_reward": {
		title: i18n.DanmakuLegacyNewAnchorReward,
		fields: []commandField{
			{"reward_id", 'i'},
			{"uid", 'i'},
		},
	},
	"NOTICE_MSG_H5": {
		title: i18n.DanmakuLegacyNoticeMsgH5,
		fields: []commandField{
			{"data.msg", 's'},
			{"data.value", 'a'},
			{"data.special_index", 'a'},
			{"data.room_id", 'i'},
			{"data.ts", 'n'},
		},
	},
	"PK_AGAIN": {
		title: i18n.DanmakuLegacyPkAgain,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.new_pk_id", 'i'},
			{"data.init_id", 'i'},
			{"data.match_id", 'i'},
			{"data.escape_all_time", 'n'},
			{"data.escape_time", 'n'},
			{"data.is_portrait", 'b'},
			{"data.uname", 's'},
			{"data.face", 's'},
			{"data.uid", 'i'},
		},
	},
	"PK_BATTLE_END": {
		title: i18n.DanmakuLegacyPkBattleEnd,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.timer", 'n'},
			{"data.init_info.room_id", 'i'},
			{"data.init_info.votes", 'n'},
			{"data.init_info.winner_type", 'n'},
			{"data.init_info.best_uname", 's'},
			{"data.match_info.room_id", 'i'},
			{"data.match_info.votes", 'n'},
			{"data.match_info.winner_type", 'n'},
			{"data.match_info.best_uname", 's'},
		},
	},
	"PK_BATTLE_ENTRANCE": {
		title: i18n.DanmakuLegacyPkBattleEntrance,
		fields: []commandField{
			{"timestamp", 'n'},
			{"data.is_open", 'b'},
		},
	},
	"PK_BATTLE_GIFT": {
		title: i18n.DanmakuLegacyPkBattleGift,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.room_id", 'i'},
			{"data.gift_id", 'i'},
			{"data.gift_msg", 's'},
		},
	},
	"PK_BATTLE_PRE": {
		title: i18n.DanmakuLegacyPkBattlePre,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.uname", 's'},
			{"data.face", 's'},
			{"data.uid", 'i'},
			{"data.room_id", 'i'},
			{"data.pre_timer", 'n'},
			{"data.pk_votes_name", 's'},
		},
	},
	"PK_BATTLE_PRO_TYPE": {
		title: i18n.DanmakuLegacyPkBattleProType,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.timer", 'n'},
			{"data.final_hit_room_id", 'i'},
			{"data.be_final_hit_room_id", 'i'},
		},
	},
	"PK_BATTLE_PROCESS": {
		title: i18n.DanmakuLegacyPkBattleProcess,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.init_info.room_id", 'i'},
			{"data.init_info.votes", 'n'},
			{"data.init_info.best_uname", 's'},
			{"data.match_info.room_id", 'i'},
			{"data.match_info.votes", 'n'},
			{"data.match_info.best_uname", 's'},
		},
	},
	"PK_BATTLE_RANK_CHANGE": {
		title: i18n.DanmakuLegacyPkBattleRankChange,
		fields: []commandField{
			{"timestamp", 'n'},
			{"data.first_rank_img_url", 's'},
			{"data.rank_name", 's'},
		},
	},
	"PK_BATTLE_SETTLE_USER": {
		title: i18n.DanmakuLegacyPkBattleSettleUser,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"settle_status", 'n'},
			{"data.settle_status", 'n'},
			{"data.result_type", 'n'},
			{"data.winner.uid", 'i'},
			{"data.winner.uname", 's'},
			{"data.winner.face", 's'},
			{"data.winner.face_frame", 's'},
			{"data.winner.exp.color", 'n'},
			{"data.winner.exp.user_level", 'n'},
			{"data.winner.exp.master_level.level", 'n'},
			{"data.winner.exp.master_level.color", 'n'},
			{"data.winner.best_user.uid", 'i'},
			{"data.winner.best_user.uname", 's'},
			{"data.winner.best_user.face", 's'},
			{"data.winner.best_user.pk_votes", 'n'},
			{"data.winner.best_user.pk_votes_name", 's'},
			{"data.winner.best_user.exp.level", 'n'},
			{"data.winner.best_user.exp.color", 'n'},
			{"data.winner.best_user.face_frame", 's'},
			{"data.winner.best_user.badge", 's'},
		},
	},
	"PK_BATTLE_SETTLE": {
		title: i18n.DanmakuLegacyPkBattleSettle,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"settle_status", 'n'},
			{"data.result_type", 'n'},
		},
	},
	"PK_BATTLE_START": {
		title: i18n.DanmakuLegacyPkBattleStart,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"timestamp", 'n'},
			{"data.final_hit_votes", 'n'},
			{"data.pk_start_time", 'n'},
			{"data.pk_frozen_time", 'n'},
			{"data.pk_end_time", 'n'},
			{"data.pk_votes_type", 'n'},
			{"data.pk_votes_add", 'n'},
			{"data.pk_votes_name", 's'},
		},
	},
	"PK_BATTLE_VOTES_ADD": {
		title: i18n.DanmakuLegacyPkBattleVotesAdd,
		fields: []commandField{
			{"timestamp", 'n'},
			{"data.type", 'n'},
			{"data.pk_votes_add", 'n'},
			{"data.pk_votes_name", 's'},
		},
	},
	"PK_CLICK_AGAIN": {
		title: i18n.DanmakuLegacyPkClickAgain,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
		},
	},
	"PK_END": {
		title: i18n.DanmakuLegacyPkEnd,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.init_id", 'i'},
			{"data.match_id", 'i'},
			{"data.punish_topic", 's'},
		},
	},
	"PK_INVITE_CANCEL": {
		title: i18n.DanmakuLegacyPkInviteCancel,
		fields: []commandField{
			{"pk_invite_status", 'n'},
			{"invite_id", 'i'},
			{"face", 's'},
			{"uname", 's'},
			{"area_name", 's'},
			{"user_level", 'n'},
			{"master_level", 'n'},
		},
	},
	"PK_INVITE_FAIL": {
		title: i18n.DanmakuLegacyPkInviteFail,
		fields: []commandField{
			{"pk_invite_status", 'n'},
			{"invite_id", 'i'},
		},
	},
	"PK_INVITE_INIT": {
		title: i18n.DanmakuLegacyPkInviteInit,
		fields: []commandField{
			{"pk_invite_status", 'n'},
			{"invite_id", 'i'},
			{"face", 's'},
			{"uname", 's'},
			{"area_name", 's'},
			{"user_level", 'n'},
			{"master_level", 'n'},
		},
	},
	"PK_INVITE_REFUSE": {
		title: i18n.DanmakuLegacyPkInviteRefuse,
		fields: []commandField{
			{"pk_invite_status", 'n'},
			{"invite_id", 'i'},
		},
	},
	"PK_INVITE_SWITCH_CLOSE": {
		title: i18n.DanmakuLegacyPkInviteSwitchClose,
	},
	"PK_INVITE_SWITCH_OPEN": {
		title: i18n.DanmakuLegacyPkInviteSwitchOpen,
	},
	"PK_LOTTERY_START": {
		title: i18n.DanmakuLegacyPkLotteryStart,
		fields: []commandField{
			{"data.asset_animation_pic", 's'},
			{"data.asset_icon", 's'},
			{"data.id", 'i'},
			{"data.max_time", 'n'},
			{"data.pk_id", 'i'},
			{"data.room_id", 'i'},
			{"data.time", 'n'},
			{"data.title", 's'},
		},
	},
	"PK_MATCH": {
		title: i18n.DanmakuLegacyPkMatch,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.init_id", 'i'},
			{"data.match_id", 'i'},
			{"data.escape_all_time", 'n'},
			{"data.escape_time", 'n'},
			{"data.is_portrait", 'b'},
			{"data.uname", 's'},
			{"data.face", 's'},
			{"data.uid", 'i'},
		},
	},
	"PK_MIC_END": {
		title: i18n.DanmakuLegacyPkMicEnd,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.type", 'n'},
			{"data.exception_id", 'i'},
		},
	},
	"PK_PRE": {
		title: i18n.DanmakuLegacyPkPre,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.init_id", 'i'},
			{"data.match_id", 'i'},
			{"data.count_down", 'n'},
			{"data.pk_topic", 's'},
			{"data.pk_pre_time", 'n'},
			{"data.pk_start_time", 'n'},
			{"data.pk_end_time", 'n'},
			{"data.end_time", 'n'},
		},
	},
	"PK_PROCESS": {
		title: i18n.DanmakuLegacyPkProcess,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.uid", 'i'},
			{"data.init_votes", 'n'},
			{"data.match_votes", 'n'},
			{"data.user_votes", 'n'},
		},
	},
	"PK_SETTLE": {
		title: i18n.DanmakuLegacyPkSettle,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.pk_id", 'i'},
			{"data.init_info.uid", 'i'},
			{"data.init_info.uname", 's'},
			{"data.init_info.face", 's'},
			{"data.init_info.votes", 'n'},
			{"data.init_info.is_winner", 'b'},
			{"data.init_info.init_id", 'i'},
			{"data.match_info.uid", 'i'},
			{"data.match_info.uname", 's'},
			{"data.match_info.face", 's'},
			{"data.match_info.votes", 'n'},
			{"data.match_info.is_winner", 'b'},
			{"data.match_info.vip_type", 'n'},
			{"data.match_info.exp.color", 'n'},
			{"data.match_info.exp.user_level", 'n'},
			{"data.match_info.exp.master_level.level", 'n'},
			{"data.match_info.exp.master_level.color", 'n'},
			{"data.match_info.vip.vip", 'n'},
			{"data.match_info.vip.svip", 'n'},
			{"data.match_info.face_frame", 's'},
			{"data.match_info.badge.url", 's'},
			{"data.match_info.badge.desc", 's'},
			{"data.match_info.badge.position", 'n'},
			{"data.match_info.match_id", 'i'},
			{"data.best_user.uid", 'i'},
			{"data.best_user.uname", 's'},
			{"data.best_user.face", 's'},
			{"data.best_user.vip_type", 'n'},
			{"data.best_user.exp.color", 'n'},
			{"data.best_user.exp.user_level", 'n'},
			{"data.best_user.exp.master_level.level", 'n'},
			{"data.best_user.exp.master_level.color", 'n'},
			{"data.best_user.vip.vip", 'n'},
			{"data.best_user.vip.svip", 'n'},
			{"data.best_user.face_frame", 's'},
			{"data.best_user.badge.url", 's'},
			{"data.best_user.badge.desc", 's'},
			{"data.best_user.badge.position", 'n'},
			{"data.best_user.privilege_type", 'n'},
			{"data.punish_topic", 's'},
		},
	},
	"PK_START": {
		title: i18n.DanmakuLegacyPkStart,
		fields: []commandField{
			{"pk_id", 'i'},
			{"pk_status", 'n'},
			{"data.init_id", 'i'},
			{"data.match_id", 'i'},
			{"data.pk_topic", 's'},
		},
	},
	"RAFFLE_END": {
		title: i18n.DanmakuLegacyRaffleEnd,
		fields: []commandField{
			{"data.id", 's'},
			{"data.uname", 's'},
			{"data.sname", 's'},
			{"data.giftName", 's'},
			{"data.mobileTips", 's'},
			{"data.raffleId", 'i'},
			{"data.type", 's'},
			{"data.from", 's'},
			{"data.fromFace", 's'},
			{"data.fromGiftId", 'n'},
			{"data.win.uname", 's'},
			{"data.win.face", 's'},
			{"data.win.giftName", 's'},
			{"data.win.giftId", 's'},
			{"data.win.giftNum", 'n'},
			{"data.win.giftImage", 's'},
			{"data.win.msg", 's'},
		},
	},
	"RAFFLE_START": {
		title: i18n.DanmakuLegacyRaffleStart,
		fields: []commandField{
			{"data.id", 's'},
			{"data.dtime", 'n'},
			{"data.msg.msg", 's'},
			{"data.msg.msg_text", 's'},
			{"data.msg.url", 's'},
			{"data.msg.msg_common", 's'},
			{"data.msg.msg_self", 's'},
			{"data.msg.rep", 'n'},
			{"data.msg.styleType", 'n'},
			{"data.msg.real_roomid", 'i'},
			{"data.msg.rnd", 'n'},
			{"data.msg.broadcast_type", 'n'},
			{"data.raffleId", 'i'},
			{"data.payflow_id", 's'},
			{"data.title", 's'},
			{"data.type", 's'},
			{"data.from", 's'},
			{"data.from_user.uname", 's'},
			{"data.from_user.face", 's'},
			{"data.time", 'n'},
			{"data.max_time", 'n'},
			{"data.time_wait", 'n'},
			{"data.asset_animation_pic", 's'},
			{"data.asset_tips_pic", 's'},
			{"data.sender_type", 'n'},
		},
	},
	"ROOM_BOX_BOOS_AWARD": {
		title: i18n.DanmakuLegacyRoomBoxBoosAward,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.h5_url", 's'},
			{"data.web_url", 's'},
			{"data.data.roomid", 'i'},
		},
	},
	"ROOM_BOX_MASTER": {
		title: i18n.DanmakuLegacyRoomBoxMaster,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.h5_url", 's'},
			{"data.data.uid", 'i'},
			{"data.data.gift_name", 's'},
			{"data.data.coin", 's'},
			{"data.data.gift_icon", 's'},
			{"data.data.start_time", 's'},
			{"data.data.end_time", 's'},
			{"data.data.pc_status", 'n'},
			{"data.data.user_uname", 's'},
		},
	},
	"ROOM_BOX_USER": {
		title: i18n.DanmakuLegacyRoomBoxUser,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.h5_url", 's'},
			{"data.data.uid", 'i'},
			{"data.data.gift_name", 's'},
			{"data.data.coin", 's'},
			{"data.data.gift_icon", 's'},
			{"data.data.start_time", 's'},
			{"data.data.end_time", 's'},
			{"data.data.type", 'n'},
			{"data.data.rate", 'n'},
		},
	},
	"ROOM_LIMIT": {
		title: i18n.DanmakuLegacyRoomLimit,
		fields: []commandField{
			{"type", 's'},
			{"delay_range", 'n'},
		},
	},
	"ROOM_LOCK": {
		title: i18n.DanmakuLegacyRoomLock,
		fields: []commandField{
			{"expire", 's'},
		},
	},
	"ROOM_RANK": {
		title: i18n.DanmakuLegacyRoomRank,
		fields: []commandField{
			{"data.roomid", 'i'},
			{"data.rank_desc", 's'},
			{"data.color", 's'},
			{"data.h5_url", 's'},
			{"data.web_url", 's'},
			{"data.timestamp", 'n'},
		},
	},
	"ROOM_SHIELD": {
		title: i18n.DanmakuLegacyRoomShield,
		fields: []commandField{
			{"type", 'n'},
			{"user", 's'},
			{"keyword", 's'},
		},
	},
	"ROOM_SKIN_MSG": {
		title: i18n.DanmakuLegacyRoomSkinMsg,
		fields: []commandField{
			{"skin_id", 'i'},
			{"status", 'n'},
			{"end_time", 'n'},
			{"current_time", 'n'},
			{"scatter.min", 'n'},
			{"scatter.max", 'n'},
		},
	},
	"SCORE_CARD": {
		title: i18n.DanmakuLegacyScoreCard,
		fields: []commandField{
			{"data.start_time", 'n'},
			{"data.end_time", 'n'},
			{"data.now_time", 'n'},
			{"data.gift_id", 'i'},
			{"data.uid", 'i'},
			{"data.ruid", 'i'},
			{"data.id", 'i'},
		},
	},
	"SPECIAL_GIFT": {
		title: i18n.DanmakuLegacySpecialGift,
		fields: []commandField{
			{"data.39.id", 'i'},
			{"data.39.time", 'n'},
			{"data.39.hadJoin", 'n'},
			{"data.39.num", 'n'},
			{"data.39.content", 's'},
			{"data.39.action", 's'},
			{"data.39.storm_gif", 's'},
		},
	},
	"SYS_GIFT": {
		title: i18n.DanmakuLegacySysGift,
		fields: []commandField{
			{"msg", 's'},
			{"rnd", 'i'},
			{"uid", 'i'},
			{"msg_text", 's'},
			{"tips", 's'},
			{"giftId", 'n'},
			{"msgTips", 'n'},
			{"url", 's'},
			{"real_roomid", 'i'},
		},
	},
	"SYS_MSG": {
		title: i18n.DanmakuLegacySysMsg,
		fields: []commandField{
			{"msg", 's'},
			{"msg_text", 's'},
			{"url", 's'},
			{"msg_common", 's'},
			{"msg_self", 's'},
			{"rep", 'n'},
			{"styleType", 'n'},
			{"real_roomid", 'i'},
			{"rnd", 'n'},
			{"broadcast_type", 'n'},
		},
	},
	"TV_END": {
		title: i18n.DanmakuLegacyTvEnd,
		fields: []commandField{
			{"data.id", 's'},
			{"data.uname", 's'},
			{"data.sname", 's'},
			{"data.giftName", 's'},
			{"data.mobileTips", 's'},
			{"data.raffleId", 'i'},
			{"data.type", 's'},
			{"data.from", 's'},
			{"data.fromFace", 's'},
			{"data.fromGiftId", 'n'},
			{"data.win.uname", 's'},
			{"data.win.face", 's'},
			{"data.win.giftName", 's'},
			{"data.win.giftId", 's'},
			{"data.win.giftNum", 'n'},
			{"data.win.giftImage", 's'},
			{"data.win.msg", 's'},
		},
	},
	"TV_START": {
		title: i18n.DanmakuLegacyTvStart,
		fields: []commandField{
			{"data.id", 's'},
			{"data.dtime", 'n'},
			{"data.msg.msg", 's'},
			{"data.msg.msg_text", 's'},
			{"data.msg.url", 's'},
			{"data.msg.msg_common", 's'},
			{"data.msg.msg_self", 's'},
			{"data.msg.rep", 'n'},
			{"data.msg.styleType", 'n'},
			{"data.msg.real_roomid", 'i'},
			{"data.msg.rnd", 'n'},
			{"data.msg.broadcast_type", 'n'},
			{"data.raffleId", 'i'},
			{"data.payflow_id", 's'},
			{"data.title", 's'},
			{"data.type", 's'},
			{"data.from", 's'},
			{"data.from_user.uname", 's'},
			{"data.from_user.face", 's'},
			{"data.time", 'n'},
			{"data.max_time", 'n'},
			{"data.time_wait", 'n'},
			{"data.asset_animation_pic", 's'},
			{"data.asset_tips_pic", 's'},
			{"data.sender_type", 'n'},
		},
	},
	"USER_GAIN_MEDAL": {
		title: i18n.DanmakuLegacyUserGainMedal,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.up_uid", 'i'},
			{"data.medal_id", 'i'},
			{"data.medal_name", 's'},
			{"data.medal_level", 'n'},
			{"data.medal_color", 'n'},
			{"data.msg_title", 's'},
			{"data.msg_content", 's'},
			{"data.normal_color", 'n'},
			{"data.highlight_color", 'n'},
		},
	},
	"USER_INFO_UPDATE": {
		title: i18n.DanmakuLegacyUserInfoUpdate,
		fields: []commandField{
			{"data.type", 'n'},
			{"data.uid", 'i'},
			{"data.room_id", 'i'},
		},
	},
	"USER_PANEL_RED_ALARM": {
		title: i18n.DanmakuLegacyUserPanelRedAlarm,
		fields: []commandField{
			{"data.module", 's'},
			{"data.alarm_num", 'n'},
		},
	},
	"USER_TITLE_GET": {
		title: i18n.DanmakuLegacyUserTitleGet,
		fields: []commandField{
			{"data.title_id", 's'},
			{"data.source", 's'},
			{"data.name", 's'},
			{"data.description", 's'},
			{"data.colorful", 'n'},
			{"data.create_time", 's'},
			{"data.expire_time", 's'},
			{"data.url", 's'},
			{"data.mobile_pic_url", 's'},
			{"data.web_pic_url", 's'},
			{"data.num", 'n'},
			{"data.score", 'n'},
			{"data.status", 'n'},
			{"data.level", 'n'},
			{"uid", 'i'},
		},
	},
	"WELCOME": {
		title: i18n.DanmakuLegacyWelcome,
		fields: []commandField{
			{"data.uid", 'i'},
			{"data.uname", 's'},
			{"data.isadmin", 'n'},
			{"data.vip", 'n'},
		},
	},
	"WELCOME_GUARD": {
		title: i18n.DanmakuLegacyWelcomeGuard,
		fields: []commandField{
			{"data.uid", 'i'},
			{"data.username", 's'},
			{"data.guard_level", 'n'},
		},
	},
	"WIN_ACTIVITY": {
		title: i18n.DanmakuLegacyWinActivity,
		fields: []commandField{
			{"number", 'n'},
			{"data.delay_time_min", 'n'},
			{"data.delay_time_max", 'n'},
		},
	},
	"WISH_BOTTLE": {
		title: i18n.DanmakuLegacyWishBottle,
		fields: []commandField{
			{"data.action", 's'},
			{"data.id", 'i'},
			{"data.wish.id", 'i'},
			{"data.wish.uid", 'i'},
			{"data.wish.type", 'n'},
			{"data.wish.type_id", 'i'},
			{"data.wish.wish_limit", 'n'},
			{"data.wish.wish_progress", 'n'},
			{"data.wish.status", 'n'},
			{"data.wish.content", 's'},
			{"data.wish.ctime", 's'},
			{"data.wish.count_map", 'a'},
		},
	},
}
