package danmaku

import "arcana-world/internal/i18n"

// Wire fields independently transcribed from bilibili-API-collect message_stream.md
// at 5e81e288579470be9aee6576dafb9ae68f766361:
// https://github.com/SocialSisterYi/bilibili-API-collect/blob/5e81e288579470be9aee6576dafb9ae68f766361/docs/live/message_stream.md
// Preserve structured lists and objects; undocumented numeric codes remain raw.
// DM_INTERACTION has both object and JSON-encoded object forms in the documentation.
var supplementalCommandSpecs = map[string]commandSpec{
	"DM_INTERACTION": {i18n.DanmakuSupplementalDmInteraction, []commandField{
		{"data.data", 'j'},
		{"data.id", 'i'},
		{"data.status", 'n'},
		{"data.type", 'n'},
	}},
	"GIFT_STAR_PROCESS": {i18n.DanmakuSupplementalGiftStarProcess, []commandField{
		{"data.tip", 's'},
		{"data.status", 'n'},
	}},
	"ONLINE_RANK_TOP3": {i18n.DanmakuSupplementalOnlineRankTop3, []commandField{
		{"data.list", 'a'},
		{"data.dmscore", 'n'},
	}},
	"POPULAR_RANK_CHANGED": {i18n.DanmakuSupplementalPopularRankChanged, []commandField{
		{"data.uid", 'i'},
		{"data.rank", 'n'},
		{"data.countdown", 'n'},
		{"data.timestamp", 'n'},
		{"data.cache_key", 's'},
	}},
	"HOT_RANK_CHANGED": {i18n.DanmakuSupplementalHotRankChanged, []commandField{
		{"data.area_name", 's'},
		{"data.rank", 'n'},
		{"data.rank_desc", 's'},
		{"data.trend", 'n'},
		{"data.countdown", 'n'},
		{"data.timestamp", 'n'},
		{"data.web_url", 's'},
		{"data.live_url", 's'},
		{"data.blink_url", 's'},
		{"data.live_link_url", 's'},
		{"data.pc_link_url", 's'},
		{"data.icon", 's'},
	}},
	"HOT_RANK_CHANGED_V2": {i18n.DanmakuSupplementalHotRankChangedV2, []commandField{
		{"data.area_name", 's'},
		{"data.rank", 'n'},
		{"data.rank_desc", 's'},
		{"data.trend", 'n'},
		{"data.countdown", 'n'},
		{"data.timestamp", 'n'},
		{"data.web_url", 's'},
		{"data.live_url", 's'},
		{"data.blink_url", 's'},
		{"data.live_link_url", 's'},
		{"data.pc_link_url", 's'},
		{"data.icon", 's'},
	}},
	"HOT_RANK_SETTLEMENT": {i18n.DanmakuSupplementalHotRankSettlement, []commandField{
		{"data.uname", 's'},
		{"data.area_name", 's'},
		{"data.rank", 'n'},
		{"data.dm_msg", 's'},
		{"data.cache_key", 's'},
		{"data.dmscore", 'n'},
		{"data.face", 's'},
		{"data.icon", 's'},
		{"data.timestamp", 'n'},
		{"data.url", 's'},
	}},
	"HOT_RANK_SETTLEMENT_V2": {i18n.DanmakuSupplementalHotRankSettlementV2, []commandField{
		{"data.uname", 's'},
		{"data.area_name", 's'},
		{"data.rank", 'n'},
		{"data.dm_msg", 's'},
		{"data.face", 's'},
		{"data.timestamp", 'n'},
		{"data.icon", 's'},
		{"data.url", 's'},
		{"data.cache_key", 's'},
	}},
	"POPULARITY_RED_POCKET_NEW": {i18n.DanmakuSupplementalPopularityRedPocketNew, []commandField{
		{"data.uname", 's'},
		{"data.uid", 'i'},
		{"data.action", 's'},
		{"data.gift_name", 's'},
		{"data.num", 'n'},
		{"data.price", 'n'},
		{"data.medal_info", 'o'},
		{"data.lot_id", 'i'},
		{"data.start_time", 'n'},
		{"data.current_time", 'n'},
		{"data.wait_num", 'n'},
		{"data.gift_id", 'i'},
		{"data.name_color", 's'},
	}},
	"FULL_SCREEN_SPECIAL_EFFECT": {i18n.DanmakuSupplementalFullScreenSpecialEffect, []commandField{
		{"data.type", 'n'},
		{"data.ids", 'a'},
		{"data.queue", 'n'},
		{"data.platform_in", 'a'},
	}},
	"AREA_RANK_CHANGED": {i18n.DanmakuSupplementalAreaRankChanged, []commandField{
		{"data.uid", 'i'},
		{"data.rank_name", 's'},
		{"data.rank", 'n'},
		{"data.conf_id", 'i'},
		{"data.icon_url_blue", 's'},
		{"data.icon_url_pink", 's'},
		{"data.icon_url_grey", 's'},
		{"data.action_type", 'n'},
		{"data.timestamp", 'n'},
		{"data.msg_id", 's'},
		{"data.jump_url_link", 's'},
		{"data.jump_url_pc", 's'},
		{"data.jump_url_pink", 's'},
		{"data.jump_url_web", 's'},
	}},
	"SUPER_CHAT_ENTRANCE": {i18n.DanmakuSupplementalSuperChatEntrance, []commandField{
		{"data.status", 'n'},
		{"data.jump_url", 's'},
		{"data.icon", 's'},
		{"data.broadcast_type", 'n'},
		{"roomid", 'i'},
	}},
	"WIDGET_BANNER": {i18n.DanmakuSupplementalWidgetBanner, []commandField{
		{"data.widget_list", 'o'},
		{"data.timestamp", 'n'},
	}},
	"WIDGET_WISH_LIST": {i18n.DanmakuSupplementalWidgetWishList, []commandField{
		{"data.wish", 'a'},
		{"data.wish_status", 'n'},
		{"data.wish_name", 's'},
		{"data.sid", 'n'},
		{"data.wish_status_info", 'a'},
	}},
	"ANCHOR_LOT_CHECKSTATUS": {i18n.DanmakuSupplementalAnchorLotCheckstatus, []commandField{
		{"data.uid", 'i'},
		{"data.reject_reason", 's'},
		{"data.id", 'i'},
		{"data.status", 'n'},
	}},
	"ANCHOR_LOT_END": {i18n.DanmakuSupplementalAnchorLotEnd, []commandField{
		{"data.id", 'i'},
	}},
	"VIDEO_CONNECTION_JOIN_START": {i18n.DanmakuSupplementalVideoConnectionJoinStart, []commandField{
		{"data.invited_uname", 's'},
		{"data.invited_uid", 'i'},
		{"data.status", 'n'},
		{"data.channel_id", 'i'},
		{"data.invited_face", 's'},
		{"data.start_at", 'n'},
		{"data.current_time", 'n'},
		{"roomid", 'i'},
	}},
	"VIDEO_CONNECTION_MSG": {i18n.DanmakuSupplementalVideoConnectionMsg, []commandField{
		{"data.toast", 's'},
		{"data.channel_id", 'i'},
		{"data.current_time", 'n'},
		{"data.dmscore", 'n'},
	}},
	"VIDEO_CONNECTION_JOIN_END": {i18n.DanmakuSupplementalVideoConnectionJoinEnd, []commandField{
		{"data.toast", 's'},
		{"data.channel_id", 'i'},
		{"data.start_at", 'n'},
		{"data.current_time", 'n'},
		{"roomid", 'i'},
	}},
	"REENTER_LIVE_ROOM": {i18n.DanmakuSupplementalReenterLiveRoom, []commandField{
		{"data.room_id", 'i'},
		{"data.request_random_sec_range", 'n'},
		{"data.reason", 'n'},
		{"roomid", 'i'},
	}},
	"PLAY_TOGETHER": {i18n.DanmakuSupplementalPlayTogether, []commandField{
		{"data.uid", 'i'},
		{"data.message", 's'},
		{"data.action", 's'},
		{"data.ruid", 'i'},
		{"data.roomid", 'i'},
		{"data.timestamp", 'n'},
		{"data.message_type", 'n'},
		{"data.jump_url", 's'},
		{"data.web_url", 's'},
		{"data.apply_number", 'n'},
		{"data.refresh_tool", 'b'},
		{"data.cur_fleet_num", 'n'},
		{"data.max_fleet_num", 'n'},
	}},
}
